os:
  - linux
language: node_js
node_js:
  - '14.17.1'
cache:
  directories:
    - "$HOME/.npm"
before_install:
    # Update NPM
    - npm install -g npm
install:
  - npm ci
  - npm link
  - npm run coveralls
